name: DREShips
version: ${project.version}
main: de.fyreum.dreships.DREShips
api-version: 1.18
authors: [Fyreum]
softdepend: [Vault, FactionsXL]
commands:
  dreships:
    aliases: ds
    description: main command